name: Build

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  packager:
    name: ${{ matrix.release-type }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release-type:
          - full
          - no-content

    steps:
      - name: Generate token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}

      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: latest

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: Cache PHP dependencies
        uses: actions/cache@v3
        id: actions-cache
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - run: composer install --prefer-dist --no-dev

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Run
        run: composer run build -- $REMOTE $PACKAGE --type=$TYPE --unstable
        env:
          REMOTE: https://${{ github.actor }}:${{ steps.generate-token.outputs.token }}@github.com/${{ github.repository_owner }}/${{ secrets.PACKAGE_PREFIX }}${{ matrix.release-type }}.git
          PACKAGE: ${{ github.repository_owner }}/${{ secrets.PACKAGE_PREFIX }}${{ matrix.release-type }}
          TYPE: ${{ matrix.release-type }}

  meta-package:
    name: Meta-package
    needs:
      - packager
    uses: ./.github/workflows/meta-package.yml
    secrets: inherit
